apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: mediawiki-db
    type: database
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: db-port
  selector:
    app: mediawiki-db
    type: database