name: deploy_mediawiki_k8s

on:
  push:
    paths:
    - 'k8s/**'
    # - '.github/workflows/**'
  pull_request:
    paths:
    - 'k8s/**'
    # - '.github/workflows/**'
      
jobs:
  deployment:  
    name: Start K8s cluster and deploy app
    # sets up kubernet and minikube for running the app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
          github token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate Minikube
        run: minikube status | grep Running

      - name: Validate Cluster
        run: kubectl get nodes

      - name: Validate default driver
        run: 'cat $MINIKUBE_HOME/.minikube/machines/minikube/config.json | jq ".DriverName" | grep none'
        
      - name: deploy mediawiki
        run: |
          echo $PWD
          kubectl apply -f ./k8s
          sleep 30
          kubectl get all
          kubectl delete -f ./k8s
          
       
       
