name: publish_mediawiki_image

on:
  push:
  #  branches: [ main ]
    paths:
    - 'mediawiki/**'
 #   - '.github/workflows/**'
  pull_request:
   # branches: [ main ]
    paths:
    - 'mediawiki/**'
  #  - '.github/workflows/**'

env:
  USERNAME: vmpuser
  IMAGE_NAME: mediawiki
  
jobs:
  mediawiki_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build mediawiki image
        run: |
          HOME_DIR=$PWD
          chmod -R 777 $HOME_DIR/mediawiki
          cd $HOME_DIR/mediawiki
          docker build . --file Dockerfile --tag $USERNAME/$IMAGE_NAME
          
      - name: Push mediawiki image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME

